---
  - name: Aborta se usuário do DB for inválido
    fail:
      msg: A variável wordpress_db_user não pode ser 'root'
    when: '{{ wordpress_db_user }} == "root"'

  - name: Instalacao do nginx e php para o funcionamento do Wordpress
    apt:
      pkg:
      - nginx
      - unzip
      - php7.4-zip
      - php-imagick
      - php7.4-curl
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-cli
      - php7.4-bcmath
      - php7.4-xml
      - php7.4-mysql
      - php7.4-common
      - php7.4-gd
      - php7.4-json
      update_cache: yes
      state: present
  
  - name: Configuracao do vhost nginx
    copy:
      src: vhost.nginx.conf
      dest: /etc/nginx/sites-enabled/default 
  
  - name : Baixando o projeto do Wordpress e descompactando 
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html
      remote_src: yes

  - name: Alterando o arquivo wp-config
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php
  
  - name: Alterando permissão da pasta /var/www/html/wordpress
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: '0755' 

  - name: restarted nginx
    service:
      name: nginx
      state: restarted